server:
  port: 8082
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    request:
      exchange:
        producer: ex.producer
      routing-key:
        producer: rk.producer
      dead-letter:
        producer: dl.producer
      parking-lot:
        producer: pl.producer
    listener:
      time-retry: 00 41 02 * * *
    retries:
      retry: 2