server:
  port: 8081
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    request:
      exchange:
        producer: ex.producer
      routing-key:
        producer: rk.producer
      dead-letter:
        producer: dl.producer
      parking-lot:
        producer: pl.producer