server:
  port: 8081
spring:
  rabbitmq:
    request:
      host: localhost
      port: 5672
      username: guest
      password: guest
      exchange:
        producer: ex.producer
      routing-key:
        producer: rk.producer
      dead-letter:
        producer: dl.procucer
      parking-lot:
        producer: pl.procucer