server:
  port: 8081
spring:
  rabbitmq:
    request:
      host: localhost
      port: 5671
      username: admin
      password: 123
      exchange:
        producer: ex.producer
      routing-key:
        producer: rk.producer
      deadletter:
        producer: dl.procucer

